# 3024 Night terminal theme for CWatch.

name = "3024 Night"

[colors]
cursor = "#a16a94"
selection = "#3a3432"
foreground = "#d6d5d4"
background = "#090300"
black = "#090300"
red = "#db2d20"
green = "#01a252"
yellow = "#fded02"
blue = "#01a0e4"
magenta = "#a16a94"
cyan = "#b5e4f4"
white = "#a5a2a2"
bright_black = "#5c5855"
bright_red = "#e8bbd0"
bright_green = "#3a3432"
bright_yellow = "#4a4543"
bright_blue = "#807d7c"
bright_magenta = "#d6d5d4"
bright_cyan = "#cdab53"
bright_white = "#f7f7f7"
search_hit_background = "#fded02"
search_hit_background_current = "#cdab53"
search_hit_foreground = "#090300"

