# Arthur terminal theme for CWatch.

name = "Arthur"

[colors]
cursor = "#d3c0a8"
selection = "#2d2d2d"
foreground = "#ddeedd"
background = "#1c1c1c"
black = "#3d352a"
red = "#cd5c5c"
green = "#86af80"
yellow = "#e8ae5b"
blue = "#6495ed"
magenta = "#deb887"
cyan = "#b0c4de"
white = "#bbaa99"
bright_black = "#554444"
bright_red = "#cc5533"
bright_green = "#88aa22"
bright_yellow = "#ffa75d"
bright_blue = "#87ceeb"
bright_magenta = "#996600"
bright_cyan = "#b0c4de"
bright_white = "#ddccbb"
search_hit_background = "#e8ae5b"
search_hit_background_current = "#86af80"
search_hit_foreground = "#1c1c1c"

