# Base16 GitHub terminal theme for CWatch.

name = "Base16 GitHub"

[colors]
cursor = "#333333"
selection = "#c8e1ff"
foreground = "#333333"
background = "#ffffff"
black = "#ffffff"
red = "#ed5a5a"
green = "#55a532"
yellow = "#c9510e"
blue = "#0066ff"
magenta = "#d73502"
cyan = "#0086b3"
white = "#333333"
bright_black = "#969896"
bright_red = "#ed5a5a"
bright_green = "#55a532"
bright_yellow = "#c9510e"
bright_blue = "#0066ff"
bright_magenta = "#d73502"
bright_cyan = "#0086b3"
bright_white = "#1d1f21"
search_hit_background = "#c9510e"
search_hit_background_current = "#55a532"
search_hit_foreground = "#ffffff"

