# Base16 Default Light terminal theme for CWatch.

name = "Base16 Default Light"

[colors]
cursor = "#282828"
selection = "#d8d8d8"
foreground = "#282828"
background = "#f8f8f8"
black = "#f8f8f8"
red = "#ab4642"
green = "#a1b56c"
yellow = "#f7ca88"
blue = "#7cafc2"
magenta = "#ba8baf"
cyan = "#86c1b9"
white = "#181818"
bright_black = "#b8b8b8"
bright_red = "#ab4642"
bright_green = "#a1b56c"
bright_yellow = "#f7ca88"
bright_blue = "#7cafc2"
bright_magenta = "#ba8baf"
bright_cyan = "#86c1b9"
bright_white = "#282828"
search_hit_background = "#f7ca88"
search_hit_background_current = "#a1b56c"
search_hit_foreground = "#f8f8f8"
