# Base16 Zenburn terminal theme for CWatch.

name = "Base16 Zenburn"

[colors]
cursor = "#dcdccc"
selection = "#4f4f4f"
foreground = "#dcdccc"
background = "#3f3f3f"
black = "#3f3f3f"
red = "#cc9393"
green = "#7f9f7f"
yellow = "#f0dfaf"
blue = "#8cd0d3"
magenta = "#dc8cc3"
cyan = "#93e0e3"
white = "#dcdccc"
bright_black = "#709080"
bright_red = "#cc9393"
bright_green = "#7f9f7f"
bright_yellow = "#f0dfaf"
bright_blue = "#8cd0d3"
bright_magenta = "#dc8cc3"
bright_cyan = "#93e0e3"
bright_white = "#ffffff"
search_hit_background = "#f0dfaf"
search_hit_background_current = "#7f9f7f"
search_hit_foreground = "#3f3f3f"

