# Base16 Material terminal theme for CWatch.

name = "Base16 Material"

[colors]
cursor = "#eeffff"
selection = "#546e7a"
foreground = "#eeffff"
background = "#263238"
black = "#263238"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#eeffff"
bright_black = "#546e7a"
bright_red = "#f07178"
bright_green = "#c3e88d"
bright_yellow = "#ffcb6b"
bright_blue = "#82aaff"
bright_magenta = "#c792ea"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
search_hit_background = "#ffcb6b"
search_hit_background_current = "#c3e88d"
search_hit_foreground = "#263238"

