# Base16 One Dark terminal theme for CWatch.

name = "Base16 One Dark"

[colors]
cursor = "#abb2bf"
selection = "#353b45"
foreground = "#abb2bf"
background = "#282c34"
black = "#282c34"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"
bright_black = "#5c6370"
bright_red = "#e06c75"
bright_green = "#98c379"
bright_yellow = "#e5c07b"
bright_blue = "#61afef"
bright_magenta = "#c678dd"
bright_cyan = "#56b6c2"
bright_white = "#ffffff"
search_hit_background = "#e5c07b"
search_hit_background_current = "#98c379"
search_hit_foreground = "#282c34"

