# Base16 Solarized Light terminal theme for CWatch.

name = "Base16 Solarized Light"

[colors]
cursor = "#657b83"
selection = "#eee8d5"
foreground = "#657b83"
background = "#fdf6e3"
black = "#fdf6e3"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#073642"
bright_black = "#839496"
bright_red = "#cb4b16"
bright_green = "#859900"
bright_yellow = "#b58900"
bright_blue = "#268bd2"
bright_magenta = "#6c71c4"
bright_cyan = "#2aa198"
bright_white = "#002b36"
search_hit_background = "#b58900"
search_hit_background_current = "#859900"
search_hit_foreground = "#fdf6e3"

