# Belafonte Night terminal theme for CWatch.

name = "Belafonte Night"

[colors]
cursor = "#968c83"
selection = "#453a39"
foreground = "#968c83"
background = "#20111b"
black = "#20111b"
red = "#be100e"
green = "#858162"
yellow = "#eaa549"
blue = "#426a79"
magenta = "#97522c"
cyan = "#989a9c"
white = "#968c83"
bright_black = "#5e5252"
bright_red = "#be100e"
bright_green = "#858162"
bright_yellow = "#eaa549"
bright_blue = "#426a79"
bright_magenta = "#97522c"
bright_cyan = "#989a9c"
bright_white = "#d5ccba"
search_hit_background = "#eaa549"
search_hit_background_current = "#be100e"
search_hit_foreground = "#20111b"
