# Blazer terminal theme for CWatch.

name = "Blazer"

[colors]
cursor = "#ffffff"
selection = "#4a4a4a"
foreground = "#ffffff"
background = "#0d1926"
black = "#000000"
red = "#b87a7a"
green = "#7ab87a"
yellow = "#b8b87a"
blue = "#7a7ab8"
magenta = "#b87ab8"
cyan = "#7ab8b8"
white = "#d9d9d9"
bright_black = "#262626"
bright_red = "#dbbdbd"
bright_green = "#bddbbd"
bright_yellow = "#dbdbbd"
bright_blue = "#bdbddb"
bright_magenta = "#dbbddb"
bright_cyan = "#bddbdb"
bright_white = "#ffffff"
search_hit_background = "#b8b87a"
search_hit_background_current = "#dbdbbd"
search_hit_foreground = "#0d1926"
