# Broadcast terminal theme for CWatch.

name = "Broadcast"

[colors]
cursor = "#ffffff"
selection = "#2b2b2b"
foreground = "#e6e1dc"
background = "#2b2b2b"
black = "#000000"
red = "#da4939"
green = "#519f50"
yellow = "#ffd24a"
blue = "#6d9cbe"
magenta = "#d0d0ff"
cyan = "#6e9cbe"
white = "#ffffff"
bright_black = "#323232"
bright_red = "#ff7b6b"
bright_green = "#83d182"
bright_yellow = "#ffff7c"
bright_blue = "#9fcef0"
bright_magenta = "#ffffff"
bright_cyan = "#a0cef0"
bright_white = "#ffffff"
search_hit_background = "#ffd24a"
search_hit_background_current = "#519f50"
search_hit_foreground = "#2b2b2b"

