# Catppuccin terminal themes for CWatch.
# Variants: latte, frappe, macchiato, mocha.

[latte]
name = "Catppuccin Latte"

[latte.colors]
cursor = "#dc8a78"
selection = "#ccd0da"
foreground = "#4c4f69"
background = "#eff1f5"
black = "#bcc0cc"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#8839ef"
cyan = "#179299"
white = "#4c4f69"
bright_black = "#acb0be"
bright_red = "#e64553"
bright_green = "#179299"
bright_yellow = "#fe640b"
bright_blue = "#209fb5"
bright_magenta = "#ea76cb"
bright_cyan = "#04a5e5"
bright_white = "#5c5f77"
search_hit_background = "#df8e1d"
search_hit_background_current = "#fe640b"
search_hit_foreground = "#eff1f5"

[frappe]
name = "Catppuccin Frappe"

[frappe.colors]
cursor = "#f2d5cf"
selection = "#414559"
foreground = "#c6d0f5"
background = "#303446"
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#81c8be"
white = "#c6d0f5"
bright_black = "#626880"
bright_red = "#ea999c"
bright_green = "#81c8be"
bright_yellow = "#ef9f76"
bright_blue = "#85c1dc"
bright_magenta = "#f4b8e4"
bright_cyan = "#99d1db"
bright_white = "#b5bfe2"
search_hit_background = "#e5c890"
search_hit_background_current = "#ef9f76"
search_hit_foreground = "#303446"

[macchiato]
name = "Catppuccin Macchiato"

[macchiato.colors]
cursor = "#f4dbd6"
selection = "#363a4f"
foreground = "#cad3f5"
background = "#24273a"
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
white = "#cad3f5"
bright_black = "#5b6078"
bright_red = "#ee99a0"
bright_green = "#8bd5ca"
bright_yellow = "#f5a97f"
bright_blue = "#7dc4e4"
bright_magenta = "#f5bde6"
bright_cyan = "#91d7e3"
bright_white = "#b8c0e0"
search_hit_background = "#eed49f"
search_hit_background_current = "#f5a97f"
search_hit_foreground = "#24273a"

[mocha]
name = "Catppuccin Mocha"

[mocha.colors]
cursor = "#f5e0dc"
selection = "#313244"
foreground = "#cdd6f4"
background = "#1e1e2e"
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#94e2d5"
white = "#cdd6f4"
bright_black = "#585b70"
bright_red = "#eba0ac"
bright_green = "#94e2d5"
bright_yellow = "#fab387"
bright_blue = "#74c7ec"
bright_magenta = "#f5c2e7"
bright_cyan = "#89dceb"
bright_white = "#bac2de"
search_hit_background = "#f9e2af"
search_hit_background_current = "#fab387"
search_hit_foreground = "#1e1e2e"
