# Dark Pastels terminal theme for CWatch.

name = "Dark Pastels"

[colors]
cursor = "#ffffff"
selection = "#4a4a4a"
foreground = "#ffffff"
background = "#000000"
black = "#000000"
red = "#ff5555"
green = "#55ff55"
yellow = "#ffff55"
blue = "#5555ff"
magenta = "#ff55ff"
cyan = "#55ffff"
white = "#bbbbbb"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#55ff55"
bright_yellow = "#ffff55"
bright_blue = "#5555ff"
bright_magenta = "#ff55ff"
bright_cyan = "#55ffff"
bright_white = "#ffffff"
search_hit_background = "#ffff55"
search_hit_background_current = "#ffaa00"
search_hit_foreground = "#000000"
