# Darkside terminal theme for CWatch.

name = "Darkside"

[colors]
cursor = "#ffffff"
selection = "#2d2d2d"
foreground = "#ffffff"
background = "#222324"
black = "#000000"
red = "#e8341c"
green = "#68c256"
yellow = "#f2d42c"
blue = "#1c98e8"
magenta = "#8e69c9"
cyan = "#1c98e8"
white = "#bababa"
bright_black = "#404040"
bright_red = "#e05a4f"
bright_green = "#77b869"
bright_yellow = "#efd64b"
bright_blue = "#387cd3"
bright_magenta = "#957bbe"
bright_cyan = "#3d97e2"
bright_white = "#ffffff"
search_hit_background = "#f2d42c"
search_hit_background_current = "#efd64b"
search_hit_foreground = "#222324"
