# Doom Peacock terminal theme for CWatch.

name = "Doom Peacock"

[colors]
cursor = "#c7c7c7"
selection = "#2d2d2d"
foreground = "#c7c7c7"
background = "#1e1e1e"
black = "#1e1e1e"
red = "#ff6c6b"
green = "#98be65"
yellow = "#ecbe7b"
blue = "#a9a1e1"
magenta = "#c678dd"
cyan = "#46d9ff"
white = "#c7c7c7"
bright_black = "#5b6268"
bright_red = "#ff6c6b"
bright_green = "#98be65"
bright_yellow = "#ecbe7b"
bright_blue = "#a9a1e1"
bright_magenta = "#c678dd"
bright_cyan = "#46d9ff"
bright_white = "#dfdfdf"
search_hit_background = "#ecbe7b"
search_hit_background_current = "#da8548"
search_hit_foreground = "#1e1e1e"
