# Doom One terminal theme for CWatch.

name = "Doom One"

[colors]
cursor = "#bbc2cf"
selection = "#3f444a"
foreground = "#bbc2cf"
background = "#282c34"
black = "#1c1f24"
red = "#ff6c6b"
green = "#98be65"
yellow = "#ecbe7b"
blue = "#51afef"
magenta = "#c678dd"
cyan = "#46d9ff"
white = "#bbc2cf"
bright_black = "#5b6268"
bright_red = "#ff6c6b"
bright_green = "#98be65"
bright_yellow = "#ecbe7b"
bright_blue = "#51afef"
bright_magenta = "#c678dd"
bright_cyan = "#46d9ff"
bright_white = "#dfdfdf"
search_hit_background = "#ecbe7b"
search_hit_background_current = "#da8548"
search_hit_foreground = "#282c34"

