# Eighties terminal theme for CWatch.

name = "Eighties"

[colors]
cursor = "#2d2d2d"
selection = "#515151"
foreground = "#d3d0c8"
background = "#2d2d2d"
black = "#2d2d2d"
red = "#f2777a"
green = "#99cc99"
yellow = "#ffcc66"
blue = "#6699cc"
magenta = "#cc99cc"
cyan = "#66cccc"
white = "#d3d0c8"
bright_black = "#747369"
bright_red = "#f2777a"
bright_green = "#99cc99"
bright_yellow = "#ffcc66"
bright_blue = "#6699cc"
bright_magenta = "#cc99cc"
bright_cyan = "#66cccc"
bright_white = "#f2f0ec"
search_hit_background = "#ffcc66"
search_hit_background_current = "#ff9900"
search_hit_foreground = "#2d2d2d"

