# Gruvbox Light terminal theme for CWatch.

name = "Gruvbox Light"

[colors]
cursor = "#3c3836"
selection = "#d5c4a1"
foreground = "#3c3836"
background = "#fbf1c7"
black = "#fbf1c7"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#7c6f64"
bright_black = "#928374"
bright_red = "#9d0006"
bright_green = "#79740e"
bright_yellow = "#b57614"
bright_blue = "#076678"
bright_magenta = "#8f3f71"
bright_cyan = "#427b58"
bright_white = "#3c3836"
search_hit_background = "#d79921"
search_hit_background_current = "#fe8019"
search_hit_foreground = "#fbf1c7"

