# Harper terminal theme for CWatch.

name = "Harper"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#a8a49d"
background = "#010101"
black = "#010101"
red = "#f8b63f"
green = "#7fb5e1"
yellow = "#d6da25"
blue = "#489e48"
magenta = "#b296c6"
cyan = "#f5bfd7"
white = "#a8a49d"
bright_black = "#726e6a"
bright_red = "#f8b63f"
bright_green = "#7fb5e1"
bright_yellow = "#d6da25"
bright_blue = "#489e48"
bright_magenta = "#b296c6"
bright_cyan = "#f5bfd7"
bright_white = "#fefbea"
search_hit_background = "#d6da25"
search_hit_background_current = "#7fb5e1"
search_hit_foreground = "#010101"

