# Hurtado terminal theme for CWatch.

name = "Hurtado"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#dbdbdb"
background = "#000000"
black = "#575757"
red = "#ff1b00"
green = "#a5e055"
yellow = "#fbe74a"
blue = "#06d9ff"
magenta = "#ff5d5d"
cyan = "#c5a3ff"
white = "#dbdbdb"
bright_black = "#262626"
bright_red = "#d51d00"
bright_green = "#a5df00"
bright_yellow = "#fbe84a"
bright_blue = "#51b4ff"
bright_magenta = "#ff5d5d"
bright_cyan = "#c5a3ff"
bright_white = "#ffffff"
search_hit_background = "#fbe74a"
search_hit_background_current = "#a5e055"
search_hit_foreground = "#000000"

