# JellyX terminal theme for CWatch.

name = "JellyX"

[colors]
cursor = "#ffffff"
selection = "#4a4a4a"
foreground = "#ffffff"
background = "#1c1c1c"
black = "#1c1c1c"
red = "#ff6c60"
green = "#a8ff60"
yellow = "#ffffb6"
blue = "#96cbfe"
magenta = "#ff73fd"
cyan = "#c6c5fe"
white = "#ffffff"
bright_black = "#6c6c6c"
bright_red = "#ffb6b0"
bright_green = "#ceffac"
bright_yellow = "#ffffcc"
bright_blue = "#b5dcff"
bright_magenta = "#ff9cfe"
bright_cyan = "#dfdffe"
bright_white = "#ffffff"
search_hit_background = "#ffffb6"
search_hit_background_current = "#ffd700"
search_hit_foreground = "#1c1c1c"
