# Later This Evening terminal theme for CWatch.

name = "Later This Evening"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#959595"
background = "#222222"
black = "#2b2b2b"
red = "#d45a60"
green = "#afba67"
yellow = "#e5d289"
blue = "#a0bad6"
magenta = "#c092d6"
cyan = "#91bfb7"
white = "#c3c3c3"
bright_black = "#454545"
bright_red = "#d3232f"
bright_green = "#aabb39"
bright_yellow = "#e5c900"
bright_blue = "#6699d0"
bright_magenta = "#ab5ed2"
bright_cyan = "#5fc0ae"
bright_white = "#ffffff"
search_hit_background = "#e5d289"
search_hit_background_current = "#afba67"
search_hit_foreground = "#222222"
