# LiquidCarbon terminal theme for CWatch.

name = "LiquidCarbon"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#afc2c2"
background = "#303030"
black = "#000000"
red = "#ff3030"
green = "#559a70"
yellow = "#ccac00"
blue = "#0099cc"
magenta = "#cc69c8"
cyan = "#7ac4cc"
white = "#bccccc"
bright_black = "#000000"
bright_red = "#ff3030"
bright_green = "#559a70"
bright_yellow = "#ccac00"
bright_blue = "#0099cc"
bright_magenta = "#cc69c8"
bright_cyan = "#7ac4cc"
bright_white = "#bccccc"
search_hit_background = "#ccac00"
search_hit_background_current = "#559a70"
search_hit_foreground = "#303030"
