# Lovelace terminal theme for CWatch.

name = "Lovelace"

[colors]
cursor = "#f8f8f2"
selection = "#44475a"
foreground = "#f8f8f2"
background = "#1e1f29"
black = "#1e1f29"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"
bright_black = "#6272a4"
bright_red = "#ff6e6e"
bright_green = "#69ff94"
bright_yellow = "#ffffa5"
bright_blue = "#d6acff"
bright_magenta = "#ff92df"
bright_cyan = "#a4ffff"
bright_white = "#ffffff"
search_hit_background = "#f1fa8c"
search_hit_background_current = "#ffffa5"
search_hit_foreground = "#1e1f29"
