# Material terminal theme for CWatch.

name = "Material"

[colors]
cursor = "#ffffff"
selection = "#546e7a"
foreground = "#eceff1"
background = "#263238"
black = "#263238"
red = "#ff5370"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#eceff1"
bright_black = "#546e7a"
bright_red = "#ff5370"
bright_green = "#c3e88d"
bright_yellow = "#ffcb6b"
bright_blue = "#82aaff"
bright_magenta = "#c792ea"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
search_hit_background = "#ffcb6b"
search_hit_background_current = "#ff5370"
search_hit_foreground = "#263238"

