# Monokai terminal theme for CWatch.

name = "Monokai"

[colors]
cursor = "#f8f8f2"
selection = "#49483e"
foreground = "#f8f8f2"
background = "#272822"
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f8"
bright_black = "#75715e"
bright_red = "#f92672"
bright_green = "#a6e22e"
bright_yellow = "#f4bf75"
bright_blue = "#66d9ef"
bright_magenta = "#ae81ff"
bright_cyan = "#a1efe4"
bright_white = "#f9f8f5"
search_hit_background = "#f4bf75"
search_hit_background_current = "#fd971f"
search_hit_foreground = "#272822"

