# N0tch2k terminal theme for CWatch.

name = "N0tch2k"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#00ff00"
background = "#000000"
black = "#000000"
red = "#cd0000"
green = "#00cd00"
yellow = "#cdcd00"
blue = "#0000ee"
magenta = "#cd00cd"
cyan = "#00cdcd"
white = "#e5e5e5"
bright_black = "#7f7f7f"
bright_red = "#ff0000"
bright_green = "#00ff00"
bright_yellow = "#ffff00"
bright_blue = "#5c5cff"
bright_magenta = "#ff00ff"
bright_cyan = "#00ffff"
bright_white = "#ffffff"
search_hit_background = "#cdcd00"
search_hit_background_current = "#00cd00"
search_hit_foreground = "#000000"

