# Neopolitan terminal theme for CWatch.

name = "Neopolitan"

[colors]
cursor = "#ffffff"
selection = "#000000"
foreground = "#ffffff"
background = "#271f19"
black = "#000000"
red = "#800000"
green = "#61ce3c"
yellow = "#fbde2d"
blue = "#253b76"
magenta = "#ff0080"
cyan = "#8da6ce"
white = "#f8f8f8"
bright_black = "#000000"
bright_red = "#ff0000"
bright_green = "#61ce3c"
bright_yellow = "#fbde2d"
bright_blue = "#253b76"
bright_magenta = "#ff0080"
bright_cyan = "#8da6ce"
bright_white = "#ffffff"
search_hit_background = "#fbde2d"
search_hit_background_current = "#ff8700"
search_hit_foreground = "#271f19"

