# Novel terminal theme for CWatch.

name = "Novel"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#3b2322"
background = "#dfdbc3"
black = "#000000"
red = "#cc0000"
green = "#009600"
yellow = "#d06b15"
blue = "#0000cc"
magenta = "#cc00cc"
cyan = "#0087cc"
white = "#cccccc"
bright_black = "#808080"
bright_red = "#cc0000"
bright_green = "#009600"
bright_yellow = "#d06b15"
bright_blue = "#0000cc"
bright_magenta = "#cc00cc"
bright_cyan = "#0087cc"
bright_white = "#ffffff"
search_hit_background = "#d06b15"
search_hit_background_current = "#009600"
search_hit_foreground = "#dfdbc3"

