# PaulMillr terminal theme for CWatch.

name = "PaulMillr"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#f8f8f8"
background = "#000000"
black = "#2a2a2a"
red = "#ff0000"
green = "#79ff0f"
yellow = "#d3bf00"
blue = "#386bd7"
magenta = "#bd00d1"
cyan = "#00aabb"
white = "#bbbbbb"
bright_black = "#666666"
bright_red = "#ff0086"
bright_green = "#66ff66"
bright_yellow = "#f3d64e"
bright_blue = "#709aed"
bright_magenta = "#db67e6"
bright_cyan = "#7adff2"
bright_white = "#ffffff"
search_hit_background = "#d3bf00"
search_hit_background_current = "#79ff0f"
search_hit_foreground = "#000000"

