# PencilLight terminal theme for CWatch.

name = "PencilLight"

[colors]
cursor = "#000000"
selection = "#d0d0d0"
foreground = "#424242"
background = "#f1f1f1"
black = "#212121"
red = "#c30771"
green = "#10a778"
yellow = "#a89c14"
blue = "#008ec4"
magenta = "#523c79"
cyan = "#20a5ba"
white = "#e0e0e0"
bright_black = "#424242"
bright_red = "#fb007a"
bright_green = "#5fd7af"
bright_yellow = "#f3e430"
bright_blue = "#20bbfc"
bright_magenta = "#6855de"
bright_cyan = "#4fb8cc"
bright_white = "#f1f1f1"
search_hit_background = "#a89c14"
search_hit_background_current = "#10a778"
search_hit_foreground = "#f1f1f1"

