# Pro terminal theme for CWatch.

name = "Pro"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#f2f2f2"
background = "#000000"
black = "#000000"
red = "#ff0000"
green = "#59d600"
yellow = "#ff9000"
blue = "#4665ff"
magenta = "#bb00bb"
cyan = "#00dadf"
white = "#ffffff"
bright_black = "#808080"
bright_red = "#ff0080"
bright_green = "#66ff00"
bright_yellow = "#ffcc00"
bright_blue = "#0071ff"
bright_magenta = "#cc00ff"
bright_cyan = "#00ffff"
bright_white = "#ffffff"
search_hit_background = "#ff9000"
search_hit_background_current = "#59d600"
search_hit_foreground = "#000000"

