# Relaxed terminal theme for CWatch.

name = "Relaxed"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#d9d9d9"
background = "#151515"
black = "#151515"
red = "#bc5653"
green = "#909d63"
yellow = "#ebc17a"
blue = "#6a8799"
magenta = "#b06698"
cyan = "#c9dfff"
white = "#d9d9d9"
bright_black = "#636363"
bright_red = "#bc5653"
bright_green = "#909d63"
bright_yellow = "#ebc17a"
bright_blue = "#6a8799"
bright_magenta = "#b06698"
bright_cyan = "#c9dfff"
bright_white = "#f5f5f5"
search_hit_background = "#ebc17a"
search_hit_background_current = "#909d63"
search_hit_foreground = "#151515"

