# Seafoam Pastel terminal theme for CWatch.

name = "Seafoam Pastel"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#d4e7d4"
background = "#243435"
black = "#757575"
red = "#825d5d"
green = "#728c62"
yellow = "#ada16d"
blue = "#4d7f82"
magenta = "#8a7267"
cyan = "#729494"
white = "#e0e0e0"
bright_black = "#8a8a8a"
bright_red = "#cf937a"
bright_green = "#98d9aa"
bright_yellow = "#fae79d"
bright_blue = "#7ac3cf"
bright_magenta = "#d6b2a1"
bright_cyan = "#ade0e0"
bright_white = "#e0e0e0"
search_hit_background = "#ada16d"
search_hit_background_current = "#728c62"
search_hit_foreground = "#243435"

