# SoftServer terminal theme for CWatch.

name = "SoftServer"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#ffffff"
background = "#242424"
black = "#000000"
red = "#a2686a"
green = "#9aa56a"
yellow = "#a3906a"
blue = "#6b8fa3"
magenta = "#6a71a3"
cyan = "#6ba58f"
white = "#99a3a3"
bright_black = "#666666"
bright_red = "#dd5c60"
bright_green = "#bfdf55"
bright_yellow = "#deb360"
bright_blue = "#62b1df"
bright_magenta = "#606edf"
bright_cyan = "#64e39c"
bright_white = "#d2e0de"
search_hit_background = "#a3906a"
search_hit_background_current = "#9aa56a"
search_hit_foreground = "#242424"

