# Solarized Darcula terminal theme for CWatch.

name = "Solarized Darcula"

[colors]
cursor = "#839496"
selection = "#073642"
foreground = "#839496"
background = "#2b2b2b"
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"
bright_black = "#002b36"
bright_red = "#cb4b16"
bright_green = "#586e75"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#6c71c4"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"
search_hit_background = "#b58900"
search_hit_background_current = "#859900"
search_hit_foreground = "#2b2b2b"

