# Sublime Snazzy terminal theme for CWatch.

name = "Sublime Snazzy"

[colors]
cursor = "#e4e4e4"
selection = "#44475a"
foreground = "#e4e4e4"
background = "#282a36"
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"
bright_black = "#686868"
bright_red = "#ff6e67"
bright_green = "#5af78e"
bright_yellow = "#f3f99d"
bright_blue = "#57c7ff"
bright_magenta = "#ff6ac1"
bright_cyan = "#9aedfe"
bright_white = "#eff0eb"
search_hit_background = "#f3f99d"
search_hit_background_current = "#ffb86c"
search_hit_foreground = "#282a36"
