# Sundried terminal theme for CWatch.

name = "Sundried"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#6e6e6e"
background = "#1a1a1a"
black = "#302b25"
red = "#a36666"
green = "#90a57d"
yellow = "#d7af87"
blue = "#7fa5bd"
magenta = "#c79ec4"
cyan = "#8adbb4"
white = "#d0d0d0"
bright_black = "#4d4d4d"
bright_red = "#d78787"
bright_green = "#afbea2"
bright_yellow = "#e4c9af"
bright_blue = "#a1bdce"
bright_magenta = "#d7beda"
bright_cyan = "#b1e7dd"
bright_white = "#efefef"
search_hit_background = "#d7af87"
search_hit_background_current = "#90a57d"
search_hit_foreground = "#1a1a1a"

