# Tinacious Design Light terminal theme for CWatch.

name = "Tinacious Design Light"

[colors]
cursor = "#000000"
selection = "#d0d0d0"
foreground = "#000000"
background = "#ffffff"
black = "#000000"
red = "#ff4050"
green = "#a4cc35"
yellow = "#ffd24e"
blue = "#66bfff"
magenta = "#f553bf"
cyan = "#26c99e"
white = "#ffffff"
bright_black = "#4a4a4a"
bright_red = "#ff4050"
bright_green = "#a4cc35"
bright_yellow = "#ffd24e"
bright_blue = "#66bfff"
bright_magenta = "#f553bf"
bright_cyan = "#26c99e"
bright_white = "#000000"
search_hit_background = "#ffd24e"
search_hit_background_current = "#a4cc35"
search_hit_foreground = "#ffffff"

