# Tinacious Design Dark terminal theme for CWatch.

name = "Tinacious Design Dark"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#ffffff"
background = "#1d1d2b"
black = "#1d1d2b"
red = "#ff4050"
green = "#a4cc35"
yellow = "#ffd24e"
blue = "#66bfff"
magenta = "#f553bf"
cyan = "#26c99e"
white = "#ffffff"
bright_black = "#4a4a4a"
bright_red = "#ff4050"
bright_green = "#a4cc35"
bright_yellow = "#ffd24e"
bright_blue = "#66bfff"
bright_magenta = "#f553bf"
bright_cyan = "#26c99e"
bright_white = "#ffffff"
search_hit_background = "#ffd24e"
search_hit_background_current = "#a4cc35"
search_hit_foreground = "#1d1d2b"

