# Tomorrow Night Eighties terminal theme for CWatch.

name = "Tomorrow Night Eighties"

[colors]
cursor = "#cccccc"
selection = "#515151"
foreground = "#cccccc"
background = "#2d2d2d"
black = "#2d2d2d"
red = "#f2777a"
green = "#99cc99"
yellow = "#ffcc66"
blue = "#6699cc"
magenta = "#cc99cc"
cyan = "#66cccc"
white = "#cccccc"
bright_black = "#999999"
bright_red = "#f2777a"
bright_green = "#99cc99"
bright_yellow = "#ffcc66"
bright_blue = "#6699cc"
bright_magenta = "#cc99cc"
bright_cyan = "#66cccc"
bright_white = "#ffffff"
search_hit_background = "#ffcc66"
search_hit_background_current = "#99cc99"
search_hit_foreground = "#2d2d2d"

