# Tomorrow Night Bright terminal theme for CWatch.

name = "Tomorrow Night Bright"

[colors]
cursor = "#eaeaea"
selection = "#424242"
foreground = "#eaeaea"
background = "#000000"
black = "#000000"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"
bright_black = "#666666"
bright_red = "#d54e53"
bright_green = "#b9ca4a"
bright_yellow = "#e7c547"
bright_blue = "#7aa6da"
bright_magenta = "#c397d8"
bright_cyan = "#70c0b1"
bright_white = "#ffffff"
search_hit_background = "#e7c547"
search_hit_background_current = "#b9ca4a"
search_hit_foreground = "#000000"

