# Ubuntu terminal theme for CWatch.

name = "Ubuntu"

[colors]
cursor = "#ffffff"
selection = "#2e3436"
foreground = "#eeeeec"
background = "#300a24"
black = "#2e3436"
red = "#cc0000"
green = "#4e9a06"
yellow = "#c4a000"
blue = "#3465a4"
magenta = "#75507b"
cyan = "#06989a"
white = "#d3d7cf"
bright_black = "#555753"
bright_red = "#ef2929"
bright_green = "#8ae234"
bright_yellow = "#fce94f"
bright_blue = "#729fcf"
bright_magenta = "#ad7fa8"
bright_cyan = "#34e2e2"
bright_white = "#eeeeec"
search_hit_background = "#c4a000"
search_hit_background_current = "#fce94f"
search_hit_foreground = "#300a24"

