# Vibrant Ink terminal theme for CWatch.

name = "Vibrant Ink"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#ffffff"
background = "#000000"
black = "#878787"
red = "#ff6600"
green = "#ccff04"
yellow = "#ffcc00"
blue = "#44b4cc"
magenta = "#9933cc"
cyan = "#44b4cc"
white = "#f5f5f5"
bright_black = "#444444"
bright_red = "#ff0000"
bright_green = "#00ff00"
bright_yellow = "#ffff00"
bright_blue = "#0000ff"
bright_magenta = "#ff00ff"
bright_cyan = "#00ffff"
bright_white = "#ffffff"
search_hit_background = "#ffcc00"
search_hit_background_current = "#ccff04"
search_hit_foreground = "#000000"

