# Wild Cherry terminal theme for CWatch.

name = "Wild Cherry"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#daf6dd"
background = "#1f1726"
black = "#000507"
red = "#d94085"
green = "#2ab250"
yellow = "#ffd16f"
blue = "#883cdc"
magenta = "#ececec"
cyan = "#c1b8b7"
white = "#fff8de"
bright_black = "#009cc9"
bright_red = "#da6bac"
bright_green = "#f4dca5"
bright_yellow = "#eac066"
bright_blue = "#308cba"
bright_magenta = "#ae636b"
bright_cyan = "#ff919d"
bright_white = "#e4838d"
search_hit_background = "#ffd16f"
search_hit_background_current = "#2ab250"
search_hit_foreground = "#1f1726"

