# Wryan terminal theme for CWatch.

name = "Wryan"

[colors]
cursor = "#ffffff"
selection = "#444444"
foreground = "#ededed"
background = "#101010"
black = "#333333"
red = "#8c4665"
green = "#287373"
yellow = "#7c7c99"
blue = "#395573"
magenta = "#5e468c"
cyan = "#31658c"
white = "#899ca1"
bright_black = "#3d3d3d"
bright_red = "#bf4d80"
bright_green = "#53a6a6"
bright_yellow = "#9e9ecb"
bright_blue = "#477ab3"
bright_magenta = "#7e62b3"
bright_cyan = "#6096bf"
bright_white = "#c0c0c0"
search_hit_background = "#7c7c99"
search_hit_background_current = "#287373"
search_hit_foreground = "#101010"

